import { baseApi } from "../../api/baseApi";

const orderApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
      createOrder: builder.mutation({
        query: (userData) => ({
          url: '/order/create',
          method: 'POST',
          body: userData,
        }),
        // Invalidate all 'Order' entries in the cache after creating an order
        invalidatesTags: ['Order'],
      }),
      orderbyTransactionId: builder.mutation({
        query: (transactionId) => ({
          url: `/order/${transactionId}`,
          method: 'POST',
        }),
        // Provide a general 'Order' tag for caching
        invalidatesTags: ['Order'],
      }),
    }),
  });
  
  // Export hooks generated by RTK Query
  export const { useCreateOrderMutation, useOrderbyTransactionIdMutation } = orderApi;
  